### ISSUE TITLE
Releases for Android, ideally also via F-Droid or APK download

### ISSUE THREAD

**Issue by Torxgewinde** [Syrex-o/FhemNative#36]
Hi there,
I would like to use FhemNative on an Android phone and avoid Google (no Playstore, no Firebase). Is there any way or interest in publishing the APK files on github or ideally via F-Droid as well? Alternatively, it would also help to publish the SHA256 of APKs distributed via Playstore to detect tampering.

Best regards

**Comment by Syrex-o** [comment]
#10

**Comment by Syrex-o** [comment]
Hi,
The request refers to a long discussion in #10.
Because the request comes from time to time and is important so users, I will create a separate package.
In order to separate the Apps, the package names will differ from store and .apk file.

**Current store package name:** de.slapapps.fhemnative
**Suggested .apk file package name (F-Droid etc):**  de.slapapps.fhemnativefree

Anything I missed? :smiley:

**Comment by Torxgewinde** [comment]
Sorry for not seeing that issue before opening this one. I will better chime in to that thread then.
